spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:15432/rag_admin?sslmode=disable
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      password: ragadmin123
      database: 0
  threads:
    virtual:
      enabled: true

rag:
  internal:
    callback-token: rag-admin-internal-callback-token
  ai:
    ollama:
      base-url: http://127.0.0.1:11434
      timeout-seconds: 180
  storage:
    minio:
      endpoint: 127.0.0.1
      port: 9000
      use-ssl: false
      access-key: minioadmin
      secret-key: minioadmin123
      bucket-name: ragadmin
      public-url: http://127.0.0.1:9000
  vector:
    milvus:
      base-url: http://127.0.0.1:19530
      token: root:Milvus
      enabled: true
